### ISSUE TITLE
Trouble installing on linux

### ISSUE THREAD

**Issue by Najarn** [nomelif/Audionodes#12]
When I check the box to enable Audionodes I get this error:
 `sean@SEAN:~/blender-2.79-linux-glibc219-x86_64$ ./blender
found bundled python: /home/sean/old_blender/blender-2.79-linux-glibc219-x86_64/2.79/python
addon_utils.disable: Audionodes-master not disabled.
Modules Installed (Audionodes-master) from '/home/sean/Downloads/Audionodes-master.zip' into '/home/sean/.config/blender/2.79/scripts/addons'
Traceback (most recent call last):
  File "/home/sean/old_blender/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/sean/.config/blender/2.79/scripts/addons/Audionodes-master/__init__.py", line 50, in <module>
    from . import blender
  File "/home/sean/.config/blender/2.79/scripts/addons/Audionodes-master/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/home/sean/.config/blender/2.79/scripts/addons/Audionodes-master/blender/ffi.py", line 13, in <module>
    native = ct.CDLL(native_path, mode=8)
  File "/home/sean/old_blender/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sean/.config/blender/2.79/scripts/addons/Audionodes-master/libnative.so: cannot open shared object file: No such file or directory
`

**Comment by ollpu** [comment]
Hi! It seems you have downloaded the addon straight as a zip of the repository, correct? This won't work because the native backend needs to be compiled. You should rather download a zip from the [releases-page](https://github.com/nomelif/Audionodes/releases), or compile the backend yourself (this is necessary to get some newer features currently). There are compilation instructions in the README.

**Comment by Najarn** [comment]
Oh ok, :) I got both last night and I must have deleted the wrong one.  Thanks for your help.

**Comment by ollpu** [comment]
I presume you've gotten it working. Reopen if not.

Also, I replaced that error message with a clearer one, explaining what's wrong and how to fix it.
