### ISSUE TITLE
Using Blender 2.91.2 Install and Running Issue

### ISSUE THREAD

**Issue by enzyme69** [nomelif/Audionodes#34]
Trying to install latest AudioNodes with Blender 2.91 and getting this error

```
Traceback (most recent call last):
  File "/Applications/BLENDER_292/Blender.app/Contents/Resources/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/Audionodes-master/__init__.py", line 32, in <module>
    from . import blender
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/Audionodes-master/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/Audionodes-master/blender/ffi.py", line 17, in <module>
    Please make sure you download the addon from the Releases-page or compile the backend yourself.""" % native_path)
AssertionError: Audionodes: Unable to locate the native backend shared library.
Expected to find it at /Users/jimmygunawan/Library/Application Support/Blender/2.91/scripts/addons/Audionodes-master/libnative.dylib.
NOTE: The addon will not work if you download a raw repository-zip, because the native backend needs to be compiled.
Please make sure you download the addon from the Releases-page or compile the backend yourself.

```

**Comment by joeyws** [comment]
I have the same problem.

**Comment by ollpu** [comment]
As the error message mentions, you should download an appropriate zip from the [releases page](https://github.com/nomelif/Audionodes/releases), not just the source code.
