### ISSUE TITLE
Can't install on Linux

### ISSUE THREAD

**Issue by Zophiekat** [nomelif/Audionodes#39]
I'm trying to install but I'm met with this error

I'm using Pop!_OS 22.04 LTS

```
Traceback (most recent call last):
  File "/home/zophiekat/.steam/debian-installation/steamapps/common/Blender/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/zophiekat/.config/blender/3.2/scripts/addons/Audionodes/__init__.py", line 32, in <module>
    from . import blender
  File "/home/zophiekat/.config/blender/3.2/scripts/addons/Audionodes/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/home/zophiekat/.config/blender/3.2/scripts/addons/Audionodes/blender/ffi.py", line 38, in <module>
    native = ct.CDLL(native_path, mode=0)
  File "/home/zophiekat/.steam/debian-installation/steamapps/common/Blender/3.2/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libfluidsynth.so.2: cannot open shared object file: No such file or directory
```

**Comment by madmadman** [comment]
same

**Comment by ghost** [comment]
same issue,
libfluidsynth1 package not available on MX linux, so I've installed:
`libfluidsynth-dev/stable,now 2.3.1-2 amd64 [installed]

libfluidsynth-static/focal,now 6:1.1.11-1kxstudio8 amd64 [installed]

libfluidsynth3/stable,now 2.3.1-2 amd64 [installed,automatic]

`
Thank you. Mmm, it's been two years, won't hold my breath 😁
