### ISSUE TITLE
Cannot install on Mac M1

### ISSUE THREAD

**Issue by enzyme69** [nomelif/Audionodes#40]
Kind of wish this nodes to work with latest Blender on Mac M1 machine. I wonder if I could try compiling this myself?

**Comment by nomelif** [comment]
It's probably worth a shot. I compiled it following the instructions on Manjaro Linux (x86_64) this morning for the latest blender and it did work.

**Comment by talsznicer** [comment]
Hello,

I wanted to compile Audionodes on my Mac Pro M1, but I had difficulty doing so and got lost in the process. However, a friend was able to help me compile it successfully. I just wanted to share this information in case someone else is facing a similar issue.

I have attached the add-on for your reference.

[Audionodes.zip](https://github.com/nomelif/Audionodes/files/11102255/Audionodes.zip)

**Comment by enzyme69** [comment]
Yeah, there is still issue:

```
Traceback (most recent call last):
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/__init__.py", line 32, in <module>
    from . import blender
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/blender/ffi.py", line 38, in <module>
    native = ct.CDLL(native_path, mode=0)
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib, 0x0002): Library not loaded: /opt/homebrew/opt/fluid-synth/lib/libfluidsynth.3.dylib
  Referenced from: <EDC74FE9-CA69-3060-97D1-C006118C0956> /Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib
  Reason: tried: '/opt/homebrew/opt/fluid-synth/lib/libfluidsynth.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/fluid-synth/lib/libfluidsynth.3.dylib' (no such file), '/opt/homebrew/opt/fluid-synth/lib/libfluidsynth.3.dylib' (no such file), '/usr/lib/libfluidsynth.3.dylib' (no such file, not in dyld cache)


```

**Comment by enzyme69** [comment]
Hey it actually works after I run this:
**brew install sdl2 fluidsynth**

Thanks!
