### ISSUE TITLE
Incompatible Architecture ARM 

### ISSUE THREAD

**Issue by enzyme69** [nomelif/Audionodes#43]
I have Audio Nodes working just earlier on this Blender 3.6x. Then I uninstalled and installed this "latest", suddenly it's not working and getting this error:

```
Traceback (most recent call last):
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/__init__.py", line 32, in <module>
    from . import blender
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/blender/ffi.py", line 38, in <module>
    native = ct.CDLL(native_path, mode=0)
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib, 0x0002): tried: '/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib' (no such file), '/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

```

Any idea why?

**Comment by ollpu** [comment]
I'm guessing you used to run Blender emulated as x86_64 under Rosetta.

**Comment by enzyme69** [comment]
I did run Blender as x86_64 sometimes for Renderman. However I tried to run AudioNodes both but not working.

**Comment by enzyme69** [comment]
I have 2 x Blender 3.6, both trying but getting different error:

```
Traceback (most recent call last):
  File "/Applications/Blender 36 Intel/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/__init__.py", line 32, in <module>
    from . import blender
  File "/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/Applications/Pixar/RenderManProServer-25.2/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/blender/ffi.py", line 38, in <module>
    native = ct.CDLL(native_path, mode=0)
  File "/Applications/Blender 36 Intel/Blender.app/Contents/Resources/3.6/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib, 0x0002): Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: <D73A5973-FAD9-3EDE-A345-E1F9321ECE03> /Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Audionodes/libnative.dylib
  Reason: tried: '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file, not in dyld cache)

```

**Comment by enzyme69** [comment]
If I use Blender 4.1 macOS ARM, could this addon works?

**Comment by enzyme69** [comment]
1) I use my MacBookPro Intel, and the addon works after I brew install the required file.
2) On my Mac Mini M2, it was working fine before, somewhat, then I uninstall and install the latest addon and somewhat it's no longer working. It's bizarre....
